StudyAbroad.Web/Models/OrderCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StudyAbroad.Web.Models
{
    public class OrderCategoryViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập tên danh mục")]
        [StringLength(120, ErrorMessage = "Tên danh mục không quá 120 ký tự")]
        public string Name { get; set; }
        public string Description { get; set; }

        [Required(ErrorMessage = "Bạn cần chọn trạng thái")]
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}

StudyAbroad.Web/Areas/Admin/Controllers/OrderCategoryController.cs
using AutoMapper;
using StudyAbroad.Data.Models;
using StudyAbroad.Repositories;
using StudyAbroad.Web.Mappings;
using StudyAbroad.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudyAbroad.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class OrderCategoryController : Controller
    {
        // GET: Admin/OrderCategory
        private readonly IOrderCategoryRepository _orderCategoryRepository;

        public OrderCategoryController(IOrderCategoryRepository OrderCategoryRepository)
        {
            _orderCategoryRepository = OrderCategoryRepository;
        }

        public ActionResult Index()
        {
            var listOrderCategory =_orderCategoryRepository.GetListOrderCategory();
            var listOrderCategoryModel = Mapper.Map<List<OrderCategory>, List<OrderCategoryViewModel>>(listOrderCategory);
            if (listOrderCategoryModel.Count() == 0)
            {
                TempData["warning"] = "Không tìm thấy bản ghi nào";
            }
            ViewBag.ListOrderCategory = listOrderCategoryModel;
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(OrderCategoryViewModel OrderCategoryModel)
        {
            if (ModelState.IsValid)
            {
                var newOrderCategory = new OrderCategory();
                newOrderCategory.UpdateOrderCategory(OrderCategoryModel);
                newOrderCategory.CreateDate = DateTime.Now;
               _orderCategoryRepository.Add(newOrderCategory);
                TempData["success"] = "Thêm mới danh mục thành công";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Thêm mới danh mục thất bại";
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var model =_orderCategoryRepository.GetOrderCategoryDetail(id);
            if (model == null)
            {
                TempData["warning"] = "Danh mục không tồn tại";
                return RedirectToAction("Index");
            }

            var viewModel = Mapper.Map<OrderCategory, OrderCategoryViewModel>(model);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(OrderCategoryViewModel OrderCategoryModel)
        {
            if (ModelState.IsValid)
            {
                var oldOrderCategory =_orderCategoryRepository.GetOrderCategoryDetail(OrderCategoryModel.ID);
                oldOrderCategory.ModifiedDate = DateTime.Now;
                oldOrderCategory.UpdateOrderCategory(OrderCategoryModel);
               _orderCategoryRepository.Update(oldOrderCategory);
                TempData["success"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }
            else
            {
                var model =_orderCategoryRepository.GetOrderCategoryDetail(OrderCategoryModel.ID);
                var viewModel = Mapper.Map<OrderCategory, OrderCategoryViewModel>(model);
                TempData["error"] = "Cập nhật danh mục thất bại";
                return View(viewModel);
            }
        }

        public ActionResult Delete(int id)
        {
            var model =_orderCategoryRepository.GetOrderCategoryDetail(id);
            if (model == null)
            {
                TempData["warning"] = "Danh mục không tồn tại";
                return RedirectToAction("Index");
            }
           _orderCategoryRepository.Delete(id);
            TempData["success"] = "Xóa danh mục thành công";
            return RedirectToAction("Index");
        }
    }
}

StudyAbroad.Web/Areas/Admin/Views/OrderCategory/Create.cshtml
@model StudyAbroad.Web.Models.OrderCategoryViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Thêm mới danh mục
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
            <li><a href="Admin/OrderCategory/Index">Danh mục</a></li>
            <li class="active">Thêm danh mục</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Create", "OrderCategory", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên danh mục</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "txtName" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Mô tả</label>
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Trạng thái</label>
                                <select class="form-control" id="Status" name="Status">
                                    <option value="1">Hoạt động</option>
                                    <option value="0">Khóa</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-4">
                                    <input type="submit" value="Thêm mới" class="btn btn-success" />
                                </div>
                                <div class="col-lg-4">
                                    <a class="btn btn-danger" href="@Url.Action("Index", "OrderCategory", new { Area = "Admin" })">Quay lại</a>
                                </div>
                            </div>
                        }

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

StudyAbroad.Web/Areas/Admin/Views/OrderCategory/Edit.cshtml
@model StudyAbroad.Web.Models.OrderCategoryViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Cập nhật danh mục
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
            <li><a href="Admin/OrderCategory/Index">Danh mục</a></li>
            <li class="active">Cập nhật danh mục</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Edit", "OrderCategory", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên danh mục</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "txtName" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Mô tả</label>
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Trạng thái</label>
                                <select class="form-control" id="Status" name="Status">
                                    @if (Model.Status == 1)
                                    {
                                        <option value="1" selected>Hoạt động</option>
                                        <option value="0">Khóa</option>
                                    }
                                    else
                                    {
                                        <option value="1">Hoạt động</option>
                                        <option value="0" selected>Khóa</option>
                                    }
                                </select>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-4">
                                    <input type="submit" value="Cập nhật" class="btn btn-success" />
                                </div>
                                <div class="col-lg-4">
                                    <a class="btn btn-danger" href="@Url.Action("Index", "OrderCategory", new { Area = "Admin" })">Quay lại</a>
                                </div>
                            </div>
                        }

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

StudyAbroad.Web/Areas/Admin/Views/OrderCategory/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ListOrderCategories = (List<StudyAbroad.Web.Models.OrderCategoryViewModel>)ViewBag.ListOrderCategory;
}

<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Quản lý danh mục tin tức
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/OrderCategory/Index">Danh mục</a></li>
            <li class="active">Danh sách danh mục</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> <a class="btn btn-primary" href="@Url.Action("Create", "OrderCategory", new { Area = "Admin" })">Thêm mới</a></h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên danh mục</th>
                                    <th>Mô tả</th>
                                    <th>Ngày tạo</th>
                                    <th>Trạng thái</th>
                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    if (ListOrderCategories.Count() > 0)
                                    {
                                        var stt = 0;
                                        foreach (var item in ListOrderCategories)
                                        {
                                            <tr>
                                                <td>@Html.Raw(stt = stt + 1)</td>
                                                <td>@item.Name</td>
                                                <td>@item.Description</td>
                                                <td>@String.Format("{0:MM/dd/yyyy}", item.CreateDate)</td>
                                                @if (item.Status == 1)
                                                {
                                                    <td><span class="btn-success">Hoạt động</span></td>
                                                }
                                                else
                                                {
                                                    <td><span class="btn-danger"> Đang khóa</span></td>
                                                }
                                                <td>
                                                    <a href="/Admin/OrderCategory/Edit/@item.ID" class="btn btn-primary glyphicon glyphicon-edit"></a>
                                                    <a class="btn btn-danger glyphicon glyphicon-trash" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","OrderCategory")/@item.ID"></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>