StudyAbroad.Web/Models/ProgramViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudyAbroad.Web.Models
{
    public class ProgramViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập tên chương trình")]
        [StringLength(120, ErrorMessage = "Tênchương trình không quá 120 ký tự")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Bạn cần nhập mô tả")]
        [StringLength(550, ErrorMessage = "Mô tả không quá 550 ký tự")]
        public string Description { get; set; }

        [AllowHtml]
        public string Detail { get; set; }


        [Required(ErrorMessage = "Bạn cần chọn ngày bắt đầu ")]
        public Nullable<System.DateTime> DateWorkStart { get; set; }

        [Required(ErrorMessage = "Bạn cần chọn ngày kết thúc ")]
        public Nullable<System.DateTime> DateWorkEnd { get; set; }

        [Required(ErrorMessage = "Bạn cần nhậpghi chú")]
        [StringLength(120, ErrorMessage = "ghi chú không quá 550 ký tự")]
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [Required(ErrorMessage = "Bạn cần chọn trạng thái ")]
        public Nullable<int> Status { get; set; }
    }
}

StudyAbroad.Web/Areas/Admin/Controllers/ProgramController.cs
using AutoMapper;
using StudyAbroad.Data.Models;
using StudyAbroad.Repositories;
using StudyAbroad.Web.Mappings;
using StudyAbroad.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudyAbroad.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class ProgramController : Controller
    {
        // GET: Admin/Program
        private readonly IProgramRepository _programRepository;
        private readonly IOrderRepository _orderRepository;

        public ProgramController(IProgramRepository programRepository, IOrderRepository orderRepository)
        {
            _programRepository = programRepository;
            _orderRepository = orderRepository;
        }

        public ActionResult Index()
        {
            var listProgram = _programRepository.GetListProgram();
            var listlistProgramModel = Mapper.Map<List<Program>, List<ProgramViewModel>>(listProgram);
            ViewBag.ListProgram = listlistProgramModel;
            if (listProgram.Count() == 0)
            {
                TempData["warning"] = "Không tìm thấy bản ghi nào";
            }
            return View();
        }
        public ActionResult Create()
        {
            var categories = _orderRepository.GetListOrderHome();
            SelectList categoryList = new SelectList(categories, "Id", "Name");
            ViewBag.categoryList = categoryList;
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProgramViewModel ProgramModel)
        {
            if (ModelState.IsValid)
            {
                var newProgram = new Program();
                newProgram.UpdateProgram(ProgramModel);
                newProgram.CreateDate = DateTime.Now;
                _programRepository.Add(newProgram);
                TempData["success"] = "Thêm mới chương trình - dịch vụ thành công";
                return RedirectToAction("Index");
            }
            else
            {
                var categories = _orderRepository.GetListOrderHome();
                SelectList categoryList = new SelectList(categories, "Id", "Name");
                ViewBag.categoryList = categoryList;

                TempData["error"] = "Thêm mới chương trình - dịch vụ thất bại";
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var model = _programRepository.GetProgramDetail(id);
            if (model == null)
            {
                TempData["warning"] = "Chương trình - Dịch vụ không tồn tại";
                return RedirectToAction("Index");
            }
            var categories = _orderRepository.GetListOrderHome();
            SelectList categoryList = new SelectList(categories, "Id", "Name");
            ViewBag.categoryList = categoryList;

            var viewModel = Mapper.Map<Program, ProgramViewModel>(model);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ProgramViewModel ProgramModel)
        {
            var categories = _orderRepository.GetListOrderHome();
            SelectList categoryList = new SelectList(categories, "Id", "Name");
            ViewBag.categoryList = categoryList;

            if (ModelState.IsValid)
            {
                var oldProgram = _programRepository.GetProgramDetail(ProgramModel.ID);
                oldProgram.ModifiedDate = DateTime.Now;
                oldProgram.UpdateProgram(ProgramModel);
                _programRepository.Update(oldProgram);
                TempData["success"] = "Cập nhật chương trình - dịch vụ thành công";
                return RedirectToAction("Index");
            }
            else
            {
                var model = _programRepository.GetProgramDetail(ProgramModel.ID);
                var viewModel = Mapper.Map<Program, ProgramViewModel>(model);
                TempData["error"] = "Cập nhật chương trình - dịch vụ thất bại";
                return View(viewModel);
            }
        }

        public ActionResult Delete(int id)
        {
            var model = _programRepository.GetProgramDetail(id);
            if (model == null)
            {
                TempData["warning"] = "Chương trình - Dịch vụ không tồn tại";
                return RedirectToAction("Index");
            }
            _programRepository.Delete(id);
            TempData["success"] = "Xóa chương trình - dịch vụ thành công";
            return RedirectToAction("Index");
        }
    }
}

StudyAbroad.Web/Controllers/ProgramController.cs
using AutoMapper;
using StudyAbroad.Data.Models;
using StudyAbroad.Repositories;
using StudyAbroad.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudyAbroad.Web.Controllers
{
    public class ProgramController : Controller
    {
        private readonly IProgramRepository _programRepository;

        public ProgramController(IProgramRepository programRepository)
        {
            _programRepository = programRepository;
        }

        // GET: Program
        public ActionResult Index(int page = 1)
        {
            int pageSize = 9;
            int totalRow = 0;
            var ProgramModel = _programRepository.GetListProgramPaging(page, pageSize, out totalRow);
            var programViewModel = Mapper.Map<IEnumerable<Program>, IEnumerable<ProgramViewModel>>(ProgramModel);
            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);
            var paginationSet = new PaginationSet<ProgramViewModel>()
            {
                Items = programViewModel,
                MaxPage = 5,
                Page = page,
                TotalCount = totalRow,
                TotalPages = totalPage
            };
            return View(paginationSet);
        }

        public ActionResult ProgramDetail(int id)
        {
            var data = _programRepository.GetProgramDetail(id);
            return View(data);
        }
    }
}

StudyAbroad.Web/Areas/Admin/Views/Program/Create.cshtml
@model StudyAbroad.Web.Models.ProgramViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section footerJS{
    <script src="~/Assets/admin/bower_components/ckeditor/ckeditor.js"></script>
    <script>

        var editor1 = CKEDITOR.replace('detail', {
            // customConfig: '/Assets/admin/bower_components/ckeditor/config.js',
        });

    </script>
}
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Thêm mới Chương trình - Dịch vụ
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/Program/Index">Chương trình - Dịch vụ</a></li>
            <li class="active">Thêm Chương trình - Dịch vụ</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Create", "Program", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            <div class="col-md-8">
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Tên Chương trình - Dịch vụ</label>
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Mô tả</label>
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Chi tiết</label>
                                    @Html.TextAreaFor(model => model.Detail, new { @class = "form-control", @id = "detail" })
                                    @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Ngày bắt đầu</label>
                                    @Html.TextBoxFor(model => model.DateWorkStart, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                                    @Html.ValidationMessageFor(model => model.DateWorkStart, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Ngày kết thúc</label>
                                    @Html.TextBoxFor(model => model.DateWorkEnd, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                                    @Html.ValidationMessageFor(model => model.DateWorkStart, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Ghi chú</label>
                                    @Html.TextAreaFor(model => model.Note, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Trạng thái</label>
                                    <select class="form-control" id="Status" name="Status">
                                        <option value="1" selected>Hoạt động</option>
                                        <option value="0">Khóa</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <div class="col-lg-4">
                                        <input type="submit" value="Thêm mới" class="btn btn-success" />
                                    </div>
                                    <div class="col-lg-4">
                                        <a class="btn btn-danger" href="@Url.Action("Index", "Program", new { Area = "Admin" })">Quay lại</a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

StudyAbroad.Web/Areas/Admin/Views/Program/Edit.cshtml
@model StudyAbroad.Web.Models.ProgramViewModel
@{
    ViewBag.Title = "Cập nhật";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section footerJS{
    <script src="~/Assets/admin/bower_components/ckeditor/ckeditor.js"></script>
    <script>

        var editor1 = CKEDITOR.replace('detail', {
            // customConfig: '/Assets/admin/bower_components/ckeditor/config.js',
        });

    </script>
}
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Cập nhật Chương trình - Dịch vụ
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/Program/Index">Chương trình - Dịch vụ</a></li>
            <li class="active">Cập nhật chương trình</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm("Edit", "Program", FormMethod.Post, new { Area = "Admin", enctype = "multipart/form-data" }))
                        {
                            <div class="col-md-8">
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Tên Chương trình - Dịch vụ</label>
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>        
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Mô tả</label>
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Chi tiết</label>
                                    @Html.TextAreaFor(model => model.Detail, new { @class = "form-control", @id = "detail" })
                                    @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Ngày bắt đầu</label>
                                    @Html.TextBoxFor(model => model.DateWorkStart, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                                    @Html.ValidationMessageFor(model => model.DateWorkStart, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Ngày kết thúc</label>
                                    @Html.TextBoxFor(model => model.DateWorkEnd, "{0:yyyy-MM-ddTHH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                                    @Html.ValidationMessageFor(model => model.DateWorkStart, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Ghi chú</label>
                                    @Html.TextAreaFor(model => model.Note, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Trạng thái</label>
                                    <select class="form-control" id="Status" name="Status">
                                        @if (Model.Status == 1)
                                        {
                                            <option value="1" selected>Hoạt động</option>
                                            <option value="0">Khóa</option>
                                        }
                                        else
                                        {
                                            <option value="1">Hoạt động</option>
                                            <option value="0" selected>Khóa</option>
                                        }
                                    </select>
                                </div>

                                <div class="form-group">
                                    <div class="col-lg-4">
                                        <input type="submit" value="Cập nhật" class="btn btn-success" />
                                    </div>
                                    <div class="col-lg-4">
                                        <a class="btn btn-danger" href="@Url.Action("Index", "Program", new { Area = "Admin" })">Quay lại</a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

StudyAbroad.Web/Areas/Admin/Views/Program/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var lstPrograms = (List<StudyAbroad.Web.Models.ProgramViewModel>)ViewBag.ListProgram;
}
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Chương trình - Dịch vụ
        </h1>
        <ol class="breadcrumb">
            <li><a href="Admin/Home/Index"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="Admin/Product/Index">Chương trình - Dịch vụ</a></li>
            <li class="active">Danh sách chương trình </li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> <a class="btn btn-primary" href="@Url.Action("Create", "Program", new { Area = "Admin" })">Thêm mới</a></h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên Chương trình - Dịch vụ</th>
                                    <th>Mô tả</th>
                                    <th>Note</th>
                                    <th>Ngày bắt đầu</th>
                                    <th>Ngày kết thúc</th>
                                    <th>Trạng thái</th>
                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    var stt = 0;
                                    foreach (var item in lstPrograms)
                                    {
                                        <tr>
                                            <td>@Html.Raw(stt = stt + 1)</td>
                                            <td>@item.Name</td>
                                            <td>@item.Description</td>
                                             <td>@item.Note</td>
                                            <td>@String.Format("{0:MM/dd/yyyy}", item.DateWorkStart)</td>
                                            <td>@String.Format("{0:MM/dd/yyyy}", item.DateWorkEnd)</td>
                                            @if (item.Status == 1)
                                            {
                                                <td><span class="btn-success">Hoạt động</span></td>
                                            }

                                            else
                                            {
                                                <td><span class="btn-danger"> Đang khóa</span></td>
                                            }
                                            <td>
                                                <a href="/Admin/Program/Edit/@item.ID" class="btn btn-primary glyphicon glyphicon-edit"></a>
                                                <a class="btn btn-danger glyphicon glyphicon-trash" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","Program")/@item.ID"></a>
                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>